sudo: false
language: node_js
install:
- npm install -g codecov
- yarn
script:
- yarn test
- yarn report:package
- istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
- codecov
notifications:
  email: false
